Make phone labels optional, add 2 new data fields to Card
mapping-action-collective/healthy-transitions-frontend pull request #49
Opened 2022-01-16 17:37 UTC by wrunion

2022-01-16 23:59 UTC, develleoper requested changes
unfortunately this will make localization impossible, as it codes English grammar into the data structure

2022-01-17 05:37 UTC, wrunion commented
> unfortunately this will make localization impossible, as it codes English grammar into the data structure @develleoper 

Oh! I may not have explained this well, but none of the text is hard-coded into the UI at all. They're all just text fields. 

So, "ext" isn't hard coded into the UI. The variable "phone_1_after" is just a string. In the example I showed, the value of the variable is literally the string "ext 302." But it could hold any string value.

Context: We had a lot of phone numbers that included text after the number, such as: 
"(503)-555-5555 ask for Annie" or "541 555-5555 press 2 and leave a message" 

I didn't want to lose that information, but the extra text was also messing up the UI formatting for phone numbers (I assume.) 

So this is a proposed solution: make a plain text field and display it after the phone number. It displays a string the user has entered. 

Does that make more sense? And does that work as a solution?

2022-01-17 06:24 UTC, wrunion commented
@develleoper Also to clarify: I haven't made any changes to the Airtable. The preview data used in this deploy is from a copy of the Airtable. I altered the copy only.

As it stands, in the prod data right now, phone numbers can include text strings. Here's an example of a current listing on prod: 
<img width="448" alt="Screen Shot 2022-01-16 at 10 19 21 PM" src="https://user-images.githubusercontent.com/49598669/149717823-44144cb5-c58b-4e66-ba3c-07f7f872c939.png">
I'm assuming that the "press 2" after the phone number will mess with formatting, so that's the problem I was trying to solve! 

I'm open to other solutions if this isn't the best one!

2022-01-18 22:47 UTC, develleoper approved these changes

2022-01-18 22:48 UTC, develleoper commented
to be clear, i understand it isn't hard-coding text, my concern was grammar and word order, but in this case it's probably fine, and we don't need to be draconian about it 😅

2022-01-18 22:50 UTC, merged